### ISSUE TITLE
RAM Requirements

### ISSUE THREAD

**Issue by veleritas** [dhimmel/integrate#10]
How much RAM is required to run the `neo4j-import.ipynb` script? On a 32 GB RAM AWS instance, the RAM gets maxed out and the cell is terminated. Based on [this post](http://blog.dhimmel.com/phd-exhibit/), it seems that your machine had 256 GB of RAM, and I was wondering if it needed that much, or if there was a way to limit RAM usage.

**Comment by veleritas** [comment]
Seems like reducing the number of concurrent workers from 6 to 2 reduced the RAM usage to 20 GB. I will therefore estimate a rough usage of 10 GB RAM per worker.

**Comment by dhimmel** [comment]
> it seems that your machine had 256 GB

You're right :8ball:. Now I have much less :smiley_cat:

According to https://github.com/neo4j/neo4j/issues/6787#issuecomment-202976538:

> From my recollection, together all 6 instances together were using approximately half of the system RAM.

So it seems like 6 instances could use 120 GB. I think a workaround could be to set `max_workers = 1` or  `max_workers = 2`. The issue is that `neo4j-import.ipynb` is slow. If you upgrade to Neo4j 3+, perhaps this step will use the bolt driver which may make this step way faster. I'd recommend the upgrade, which could be as easy as changing `neo4j_version = 'neo4j-community-3.0.6'` and adapting to the consolidated config.

**Comment by dhimmel** [comment]
> Seems like reducing the number of concurrent workers from 6 to 2 reduced the RAM usage to 20 GB. I will therefore estimate a rough usage of 10 GB RAM per worker.

+1 you beat me to it

**Comment by dhimmel** [comment]
Depending on how much improvement you'd like to make, I think running Neo4j in a Docker container is the way to go.

**Comment by veleritas** [comment]
Which "consolidated config" are you referring to? I'll try running things with the latest neo4j and see if that changes anything.

**Comment by veleritas** [comment]
Do you have an estimate on how long the neo4j import takes? I think the AWS machines tend to be a bit faster (the permute step took 3 hours instead of the 4 quoted in the original notebook).

**Comment by dhimmel** [comment]
> I think the AWS machines tend to be a bit faster

Likely true... I had AMD technology (:

> Do you have an estimate on how long the neo4j import takes?

12-24 hours maybe per worker. YMMV

> Which "consolidated config" are you referring to?

I think `neo4j-server.properties` and `neo4j.properties` were merged in Neo4j 3.0. Also the default database location changed.

**Comment by veleritas** [comment]
As a benchmark for future reference, running all six workers with `max_workers=4` on an AWS r3.4xlarge instance (16 cores, 122 GB RAM) took 23 hours. Peak RAM usage seemed to be around 100 GB, so I estimate around 25 GB RAM usage per worker.
