### ISSUE TITLE
Bias in Anatomy–downregulates–Gene and Anatomy–upregulates–Gene edges

### ISSUE THREAD

**Issue by annabreit** [dhimmel/integrate#14]
Hi Daniel,

If I understand it correctly, you used the information about over-/under-expression from Bgee to create your Anatomy–downregulates–Gene and Anatomy–upregulates–Gene edges [[1](https://think-lab.github.io/d/124/)]. These values provided by Bgee refer to over-/under-expression across anatomy but also over-/under-expression across life stages [[2](https://bgee.org/?page=doc&action=call_files#single_diff_simple_col7)]. However, you are using only data from adults and therefore do not provide the life stage in your anatomy nodes. Could this in your opinion produce a bias in your network or affect it or predictions etc in any other way?

**Comment by annabreit** [comment]
Nevermind, just found that it was possible to distinguish between these two cases in version 13 (which you used), wasn't that clear from the documentation provided by bgee

**Comment by dhimmel** [comment]
Thanks @annabreit for your comments.

Looking back at [this excerpt](https://think-lab.github.io/d/124/#6), you are correct that the _Antomy-expresses-Gene_ edges in the network were observed from adult samples only:

> Using the simple dataset, I found all gene–anatomy pairs where Expression is present and Call quality is high quality for any adult developmental stage. To identify adult developmental stages, I filtered for `HsapDv:0000087` and its descendants.

The _Anatomy-up/down-regulates-Gene_ genes, are not just from adult samples, if I understand correctly from this [excerpt](http://web.archive.org/web/20160126111150/https://bgee.org/?page=doc&action=call_files#single_diff):

> Bgee provides calls of over-/under-expression. A call corresponds to a gene, with significant variation of its level of expression, in an anatomical entity during a developmental stage, as compared to, either: i) other anatomical entities at the same (broadly defined) developmental stage (over-/under-expression across anatomy);

Whether the developmental stage of expression samples affects Hetionet and its applications, I am not sure. While developmental stage likely is important for expression, the high level of noise in expression-derived data may overwhelm the bias of focusing only on adult stages. The effect probably depends on the application. For Project Rephetio, most of the [diseases](https://het.io/repurpose/) were adult diseases. Furthermore, paths containing _Anatomy-expresses-Gene_ edges played a [limited role](https://het.io/repurpose/metapaths.html) in our predictions.

> Nevermind, just found that it was possible to distinguish between these two cases in version 13 (which you used), wasn't that clear from the documentation provided by bgee

Hopefully, you can filter for the stages you'd like for your application.
