### ISSUE TITLE
Managing dependencies

### ISSUE THREAD

**Issue by veleritas** [dhimmel/integrate#9]
How are we supposed to install the `hetio` package which is part of the repo's dependencies? The `environment.yml` file has a hard coded path `(/home/dhimmels/Documents/github/hetio)==0.1.0`.

I tried downloading version 0.1.0 of the `hetio` package from https://github.com/dhimmel/hetio/releases and changing the hard coded path to the local path instead, but received the following error when trying to run `conda env create -f environment.yml`:

```
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
Invalid requirement: 'hetio (/home/ubuntu/hetio)==0.1.0'
It looks like a path. Does it exist ?
CondaValueError: Value error: pip returned an error.
```

Any ideas? I have also tried to install from the github directly instead of using a local path, but I get a dependency error with `pypandoc` instead (i.e. in `environment.yml` have the following line: `- "--editable=git+https://github.com/dhimmel/hetio.git#egg=hetio"`) see [this issue](https://github.com/dhimmel/hetio/issues/2).

**Comment by dhimmel** [comment]
Okay can you now try:

```
conda env create --file environment.yml
```

One issue is that the environment is not cross-platform compatible ([related comment on issue](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/#comment-2861241814)). It works on Linux, but currently not on Mac, which produces the following error message:

```
Error: Packages missing in current osx-64 channels: 
  - fontconfig 2.11.1 5
  - libgfortran 3.0 0
  - numpy 1.10.4 py35_1
  - scipy 0.17.0 np110py35_2
```

@veleritas are you on linux?

**Comment by veleritas** [comment]
Yes, I'm on Ubuntu 16.04. Works without any problems now, thanks!
